const mockUsers = [
  { id: 'user_001', name: 'Ali' },
  { id: 'user_002', name: 'Fatima' },
  { id: 'user_003', name: 'Usman' },
  { id: 'user_004', name: 'Ayesha' },
  { id: 'user_005', name: 'Zara' },
  { id: 'user_006', name: 'Ahmed' },
  { id: 'user_007', name: 'Sara' },
  { id: 'user_008', name: 'Bilal' },
  { id: 'user_009', name: 'Hina' },
  { id: 'user_010', name: 'Hamza' },
  { id: 'user_011', name: 'Tariq' },
  { id: 'user_012', name: 'Nida' },
  { id: 'user_013', name: 'Imran' },
  { id: 'user_014', name: 'Mariam' },
  { id: 'user_015', name: 'Raza' },
  { id: 'user_016', name: 'Noor' },
  { id: 'user_017', name: 'Asim' },
  { id: 'user_018', name: 'Lubna' },
  { id: 'user_019', name: 'Faraz' },
  { id: 'user_020', name: 'Anum' },
  { id: 'user_021', name: 'Hassan' },
  { id: 'user_022', name: 'Rabia' },
  { id: 'user_023', name: 'Jawad' },
  { id: 'user_024', name: 'Sana' },
  { id: 'user_025', name: 'Omar' },
  { id: 'user_026', name: 'Laiba' },
  { id: 'user_027', name: 'Zain' },
  { id: 'user_028', name: 'Iqra' },
  { id: 'user_029', name: 'Salman' },
  { id: 'user_030', name: 'Hira' },
];

module.exports = mockUsers;
