name: Run Backend Tests

on: [push]


jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Create .env file for test environment
        run: |
          echo "API_KEY=superSecret123" >> .env
          echo "CACHE_TTL=60" >> .env

      - name: Run Jest tests with coverage
        run: npm test -- --coverage
